export const GET_THEME_FIELD = 'GET_THEME_FIELD';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_DOCUMENTS = 'GET_DOCUMENTS';
export const GET_RESULT = 'GET_RESULT';
export const GET_FILTERED_DOCS = 'GET_FILTERED_DOCS';
